### ISSUE TITLE
RuntimeError: sox FAIL bass

### ISSUE THREAD

**Issue by matteocastagnaro** [dodiku/noise_reduction#4]
Hi, when i launch your tool, system return this error
```
Traceback (most recent call last):
  File "noise.py", line 230, in <module>
    y_reduced_centroid_s = reduce_noise_centroid_s(y, sr)
  File "noise.py", line 64, in reduce_noise_centroid_s
    y_cleaned = less_noise(y)
  File "/home/user/Documenti/RESEARCH/noise_reduction/venv/lib/python3.5/site-packages/pysndfx/dsp.py", line 276, in __call__
    raise RuntimeError(stderr.decode())
RuntimeError: sox FAIL bass: usage: gain [frequency(100) [width[s|h|k|q|o]](0.5s)]
```
How could I resolve this problem?
Thanks

**Comment by aliakbar09a** [comment]
Have you found solution for this?

**Comment by Axeltherabbit** [comment]
._. I hate this, what's the solution?

**Comment by joaoeudes7** [comment]
Solution??

**Comment by sabetAI** [comment]
https://github.com/dodiku/noise_reduction/issues/1#issuecomment-404081338
